import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const inter = Oswald({ display: "swap", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Paint Brush",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
